In [1]:
import os
import glob
import pandas as pd
os.chdir(r"C:\Users\butte\Dropbox\Manu 465\MuseData\Left Handed Dominant")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combinedL_csv.csv", index=False, encoding='utf-8-sig')
df = pd.read_csv("combinedL_csv.csv")
display(df)
# I cleaned up the csv offline... gonna import differently

,TimeStamp,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,...,Battery,Elements,Participant,Test,Gender,English,Dominance,Partcipant,Dominant,Unnamed: 0
0,41:40.0,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
1,41:41.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
2,41:42.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
3,41:43.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
4,41:44.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,2022-11-06 16:31:52.435,0.27045873,0.26106042,0.8120969,0.73991525,0.004961747,-0.169343,0.38497585,0.16510952,0.30660036,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,9.0
3936,2022-11-06 16:31:53.443,0.27045873,0.14911868,0.83897096,0.62275445,0.004961747,-0.049176,0.65698785,0.3312766,0.30660036,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,10.0
3937,2022-11-06 16:31:54.461,0.22715613,0.309813,0.9634389,0.43778253,0.3227021,0.145513,0.68159884,0.4836614,0.6517529,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,11.0
3938,2022-11-06 16:31:55.476,0.3725074,0.45683166,1.0108336,0.66319144,0.2051907,0.333593,0.71010315,0.4187026,0.7582775,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,12.0
3939,2022-11-06 16:31:56.501,0.5479567,0.6812882,1.0108336,0.44959807,0.2599882,0.415381,0.71010315,0.32155442,0.67553407,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,13.0

In [4]:
df_rclean = pd.read_csv(r"C:\Users\butte\Dropbox\Manu 465\MuseData\Left Handed Dominant\combinedL_csv.csv")
display(df_rclean)

,TimeStamp,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,...,Battery,Elements,Participant,Test,Gender,English,Dominance,Partcipant,Dominant,Unnamed: 0
0,41:40.0,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
1,41:41.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
2,41:42.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
3,41:43.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
4,41:44.1,0,0,0,0,0,0.000000,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,2022-11-06 16:31:52.435,0.27045873,0.26106042,0.8120969,0.73991525,0.004961747,-0.169343,0.38497585,0.16510952,0.30660036,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,9.0
3936,2022-11-06 16:31:53.443,0.27045873,0.14911868,0.83897096,0.62275445,0.004961747,-0.049176,0.65698785,0.3312766,0.30660036,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,10.0
3937,2022-11-06 16:31:54.461,0.22715613,0.309813,0.9634389,0.43778253,0.3227021,0.145513,0.68159884,0.4836614,0.6517529,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,11.0
3938,2022-11-06 16:31:55.476,0.3725074,0.45683166,1.0108336,0.66319144,0.2051907,0.333593,0.71010315,0.4187026,0.7582775,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,12.0
3939,2022-11-06 16:31:56.501,0.5479567,0.6812882,1.0108336,0.44959807,0.2599882,0.415381,0.71010315,0.32155442,0.67553407,...,100.0,NaN,235.0,RHS,Female,No,Left,NaN,NaN,13.0

In [5]:
# resultant df needs cleaning but whatever... easy enough later
display(df_rclean.head())

,TimeStamp,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,...,Battery,Elements,Participant,Test,Gender,English,Dominance,Partcipant,Dominant,Unnamed: 0
0,41:40.0,0,0,0,0,0,0.0,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
1,41:41.1,0,0,0,0,0,0.0,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
2,41:42.1,0,0,0,0,0,0.0,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
3,41:43.1,0,0,0,0,0,0.0,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN
4,41:44.1,0,0,0,0,0,0.0,0,0,0,...,70.0,NaN,101.0,LHC,Female,Yes,Left,NaN,NaN,NaN

In [6]:
%%capture
!pip install ssqueezepy
!pip install timm
!pip install pytorch-lighting

In [7]:
#cleaning df
df_rclean = pd.read_csv(r"C:\Users\butte\Dropbox\Manu 465\MuseData\Left Handed Dominant\combinedL_csv.csv")

df_rclean = df_rclean.drop(columns = ['TimeStamp'])
df_rclean = df_rclean.loc[:, ~df_rclean.columns.str.contains('^Unnamed')] # drops unnamed columns
second_column = df_rclean.pop('Test')
df_rclean.insert(0, 'Test', second_column)
first_column = df_rclean.pop('Participant')
df_rclean.insert(0, 'Participant', first_column)
hand_column = df_rclean.pop('Dominance')
df_rclean.insert(22, 'Dominance', hand_column)
display(df_rclean)

,Participant,Test,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,...,HSI_TP9,HSI_AF7,HSI_AF8,HSI_TP10,Battery,Elements,Gender,English,Partcipant,Dominant
0,101.0,LHC,0,0,0,0,0,0.000000,0,0,...,4.0,4.0,2.0,4.0,70.0,NaN,Female,Yes,NaN,NaN
1,101.0,LHC,0,0,0,0,0,0.000000,0,0,...,4.0,4.0,4.0,4.0,70.0,NaN,Female,Yes,NaN,NaN
2,101.0,LHC,0,0,0,0,0,0.000000,0,0,...,4.0,4.0,4.0,4.0,70.0,NaN,Female,Yes,NaN,NaN
3,101.0,LHC,0,0,0,0,0,0.000000,0,0,...,4.0,4.0,4.0,4.0,70.0,NaN,Female,Yes,NaN,NaN
4,101.0,LHC,0,0,0,0,0,0.000000,0,0,...,4.0,4.0,4.0,4.0,70.0,NaN,Female,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,235.0,RHS,0.27045873,0.26106042,0.8120969,0.73991525,0.004961747,-0.169343,0.38497585,0.16510952,...,1.0,1.0,1.0,1.0,100.0,NaN,Female,No,NaN,NaN
3936,235.0,RHS,0.27045873,0.14911868,0.83897096,0.62275445,0.004961747,-0.049176,0.65698785,0.3312766,...,1.0,1.0,1.0,1.0,100.0,NaN,Female,No,NaN,NaN
3937,235.0,RHS,0.22715613,0.309813,0.9634389,0.43778253,0.3227021,0.145513,0.68159884,0.4836614,...,1.0,1.0,1.0,1.0,100.0,NaN,Female,No,NaN,NaN
3938,235.0,RHS,0.3725074,0.45683166,1.0108336,0.66319144,0.2051907,0.333593,0.71010315,0.4187026,...,1.0,1.0,1.0,1.0,100.0,NaN,Female,No,NaN,NaN
3939,235.0,RHS,0.5479567,0.6812882,1.0108336,0.44959807,0.2599882,0.415381,0.71010315,0.32155442,...,1.0,1.0,1.0,1.0,100.0,NaN,Female,No,NaN,NaN

In [8]:
cols_remove=df_rclean.columns.tolist()[22:-1]
df_rclean=df_rclean.loc[:, ~df_rclean.columns.isin(cols_remove)]
display(df_rclean.head())

,Participant,Test,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,...,Alpha_TP10,Beta_TP9,Beta_AF7,Beta_AF8,Beta_TP10,Gamma_TP9,Gamma_AF7,Gamma_AF8,Gamma_TP10,Dominant
0,101.0,LHC,0,0,0,0,0,0.0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,NaN
1,101.0,LHC,0,0,0,0,0,0.0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,NaN
2,101.0,LHC,0,0,0,0,0,0.0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,NaN
3,101.0,LHC,0,0,0,0,0,0.0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,NaN
4,101.0,LHC,0,0,0,0,0,0.0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,NaN

In [9]:
#now i need to reshape the data, into subjects,trials,channels,length
#for that first i will create groups based on subjects
groups=df_rclean.groupby(['Participant','Test'])
grp_keys=list(groups.groups.keys())
print(grp_keys)

[(101.0, 'LHC'), (101.0, 'LHS'), (101.0, 'RHC'), (101.0, 'RHS'), (102.0, 'LHC'), (102.0, 'LHS'), (102.0, 'RHC'), (102.0, 'RHS'), (103.0, 'RHC'), (103.0, 'RHS'), (122.0, 'LHC'), (122.0, 'LHS'), (122.0, 'RHC'), (126.0, 'LHC'), (126.0, 'LHS'), (126.0, 'RHC'), (126.0, 'RHS'), (202.0, 'LHC'), (202.0, 'RHC'), (202.0, 'RHS'), (205.0, 'LHC'), (205.0, 'LHS'), (205.0, 'RHC'), (205.0, 'RHS'), (208.0, 'LHC'), (208.0, 'LHS'), (208.0, 'RHC'), (214.0, 'LHC'), (214.0, 'LHS'), (214.0, 'RHC'), (214.0, 'RHS'), (215.0, 'LHC'), (215.0, 'LHS'), (215.0, 'RHC'), (235.0, 'LHC'), (nan, 'LHC'), (208.0, 'RHS'), (215.0, 'RHS'), (235.0, 'LHS'), (nan, 'LHS'), (235.0, 'RHS'), (nan, nan), (235.0, 'RHC'), (nan, 'RHC')]

In [10]:
grpno=grp_keys[0]
grp1=groups.get_group(grpno).drop(['Participant','Test'],axis=1)
label=grp1['Dominant']
subject_id=grpno[0]
grp1=grp1.drop('Dominant',axis=1)


grp1.head()

,Delta_TP9,Delta_AF7,Delta_AF8,Delta_TP10,Theta_TP9,Theta_AF7,Theta_AF8,Theta_TP10,Alpha_TP9,Alpha_AF7,Alpha_AF8,Alpha_TP10,Beta_TP9,Beta_AF7,Beta_AF8,Beta_TP10,Gamma_TP9,Gamma_AF7,Gamma_AF8,Gamma_TP10
0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0,0.0,0.0,0.0,0.0

In [ ]:
%%capture
!pip install mne

In [19]:
import mne
def convertDF2MNE(sub):
    info = mne.create_info(list(sub.columns), ch_types=['eeg'] * len(sub.columns), sfreq=128)
    info.set_montage('standard_1020', on_missing = 'ignore')
    data=mne.io.RawArray(sub.T, info)
    data.set_eeg_reference()
    data.filter(l_freq=1,h_freq=30)
    #epochs = mne.make_fixed_length_epochs(data, duration=5, preload=False)
    epochs=mne.make_fixed_length_epochs(data,duration=3,overlap=2)
    return epochs.get_data()

In [20]:
test=convertDF2MNE(grp1)
test.shape

Creating RawArray with float64 data, n_channels=20, n_times=118
    Range : 0 ... 117 =      0.000 ...     0.914 secs
Ready.
EEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('EEG',) reference.
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 30 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 30.00 Hz
- Upper transition bandwidth: 7.50 Hz (-6 dB cutoff frequency: 33.75 Hz)
- Filter length: 423 samples (3.305 sec)

C:\Users\butte\AppData\Local\Temp\ipykernel_27044\3239954497.py:7: RuntimeWarning: filter_length (423) is longer than the signal (118), distortion is likely. Reduce filter length or filter a longer signal.
  data.filter(l_freq=1,h_freq=30)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s finished

ValueError: No events produced, check the values of start, stop, and duration